### ISSUE TITLE
Recommended contentSecurityPolicy settings 

### ISSUE THREAD

**Issue by vsymguysung** [plyfe/ember-social#14]
I am getting many errors related with the Content Security Policy.
I knew I could set the ```contentSecurityPolicy``` in the ```config/environment.js``` but I couldn't figure out exact settings.
Any recommendations?

**Comment by lukemelia** [comment]
@vsymguysung I'm afraid I don't know the answer to that. If you dig up useful information, please open a PR with changes to the README
