### ISSUE TITLE
get tests passing on travis

### ISSUE THREAD

**Issue by lukemelia** [plyfe/ember-social#18]
Not sure what the issue is here. I believe @chrislopresto has investigated a bit.

**Comment by chrislopresto** [comment]
I have SSL-related phantom failures locally, but they might be unrelated to the phantom failures on Travis.

I'm hoping to resolve my environment issues and take a look at the underlying problem(s) tomorrow.

**Comment by chrislopresto** [comment]
Just put up #19 which fixes the test failures by upgrading to PhantomJS 2.0.0.
