### ISSUE TITLE
Facebook Facepile not rendering

### ISSUE THREAD

**Issue by ksin** [plyfe/ember-social#23]
`ember serve` the dummy app. Facepile doesn't show:
* without parameters - nothing shows
* custom URL - facebook icon and likes shown. No faces.
* with theme - only a black bar shows for 'dark' theme.

**Comment by elwayman02** [comment]
:+1: still an issue

**Comment by elwayman02** [comment]
Facepile has a failing test, might be related @ksin?

**Comment by ksin** [comment]
Most likely! I don't have time to look at this lately, but yeah, that component definitely needs an audit.
