### ISSUE TITLE
Add shared event on facebook-share

### ISSUE THREAD

**Issue by denneralex** [plyfe/ember-social#27]
Hey guys, thanks for the nice plugin.

Is there any plan to add the shared event on facebook-share?

Can we add the event on this line?

https://github.com/plyfe/ember-social/blob/38cea5b8bd1a78a217f2074dac8a4aed564a148a/addon/components/facebook-share.js#L60

I know facebook send the same response even if the dialog was closed, but for now I need this in a situation I have and maybe others can have the same case. Also if the user is logged-in on your app facebook then confirm the post with a post_id on the response.

If it's ok and a PR helps, lemme know!!

**Comment by ksin** [comment]
@denneralex Sounds like a good idea. A PR would help. Thanks!
