### ISSUE TITLE
Deprecation warnings on Ember 2.7.0

### ISSUE THREAD

**Issue by sevab** [plyfe/ember-social#45]
Some deprecation warnings are thrown in regards to services when using the addon with Ember 2.7.0.

![screen shot 2016-09-09 at 12 02 33](https://cloud.githubusercontent.com/assets/3999613/18385838/c4ab7824-768a-11e6-8e3f-c44753ed89e0.png)

**Comment by ianpetzer** [comment]
@sevab Was also just looking at this.
I think it might be fixed by this: https://github.com/plyfe/ember-social/pull/43

**Comment by sevab** [comment]
@ianpetzer thanks! Upgraded to `ba826017b6a62a53d5a5cdb5145e00941d95de91`, and the first one is now fixed, although still getting `isServiceFactory` deprecation.

**Comment by sevab** [comment]
https://github.com/plyfe/ember-social/commit/76fc2fa0858791b7e3a62b2a161b5ef965e0572a fixes everything.
