### ISSUE TITLE
Variable as `tweet-id` Parameter

### ISSUE THREAD

**Issue by swcraig** [plyfe/ember-social#49]
Hi there,

Is there any way to pass a variable as the tweet-id argument? For example...

The following code snippets do not work for me; in both cases where `myTweetId` is a `number` and the case where it is a `string`.

`{{twitter-card tweet-id='myTweetId'}}`
`{{twitter-card tweet-id=myTweetId}}`

The code shown in the documentation `{{twitter-card tweet-id='463440424141459456'}}` works for me.
Am I missing something here?

Thank you!

**Comment by ksin** [comment]
`tweet-id` should be a string. I just tested passing it in as a variable and it works fine for any valid tweet id. Can you provide more code or context?

**Comment by swcraig** [comment]
As per usual, I was missing something. I made a type error with Firebase and Ember Data.

Thank you for getting back to me!
