### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by jerocosta** [plyfe/ember-social#50]
Hi guys, 

I´m getting an error when I trying to share on Facebook. 

`sdk.js:33 Uncaught SyntaxError: Unexpected identifier
`
I recently double check and the same error happens running the Dummy App on the repo. 

Thanks!

**Comment by jerocosta** [comment]
It was a Facebook SDK issue. It´s working now.

**Comment by locks** [comment]
@jerocosta thanks for following up, and for saving the maintainers work ;)
